### ISSUE TITLE
安装之后出现Trying to get property of non-object的问题，请问怎么解决

### ISSUE THREAD

**Issue by lixuemn** [moon-zhangyue/TP5#1]
![image](https://user-images.githubusercontent.com/29516709/42196991-519f6380-7eb3-11e8-91b0-015c1b223ec9.png)

**Comment by moon-zhangyue** [comment]
不好意思啊,没看到,这个项目很久了,我也记不清了,你要是想学,可以去找找这个慕课视频学习,要是找不到,我可以分享给你.有一套完整的视频的
